# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

# Ensure role dependencies are in place
if [ "up", "provision" ].include?(ARGV.first) &&
  !(File.directory?("roles/azavea.git") || File.symlink?("roles/azavea.git")) ||
  !(File.directory?("roles/azavea.nginx") || File.symlink?("roles/azavea.nginx")) ||
  !(File.directory?("roles/azavea.php-fpm") || File.symlink?("roles/azavea.php-fpm")) ||
  !(File.directory?("roles/azavea.mysql") || File.symlink?("roles/azavea.mysql"))

  unless system("ansible-galaxy install --force -r roles.txt -p roles")
    $stderr.puts "\nERROR: Please install Ansible 1.4.2+ so that the ansible-galaxy binary"
    $stderr.puts "is available."
    exit(1)
  end
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "site.yml"
    ansible.sudo = true
  end
end
